---
- name: update docker-py
  pip: name="docker-py" state="latest"

- name: update integration data records
  docker_container:
    name: "integrationator"
    image: "{{ integrationator_repo }}:{{ docker_tag }}"
    command: >-
      -l {{ ldap_host }} -h {{ db_host }} -p {{ db_port }} -d {{ db_name }} -U {{ db_user }} -P {{ db_password }}
    pull: True
    detach: False
    interactive: True

- name: wait for the process to finish
  shell: "docker wait integrationator"

- name: remove the integrationator container
  docker_container: name="integrationator" state="absent"
