---
- name: install docker-py
  pip: name="docker-py" state="present"

- name: pull the tool registration docker image
  shell: docker pull {{tool_registration_repo}}:{{docker_tag}}

- name: pull the configuration docker image
  shell: docker pull {{config_repo}}:{{docker_tag}}

- name: delete the configuration container if it exists
  shell: docker rm tool-registration-configs || echo "good, no leftover containers"

- name: create the configuration container
  shell: docker create --name tool-registration-configs {{config_repo}}:{{docker_tag}}

- name: register existing DE tools
  shell: >-
    docker run --rm --volumes-from tool-registration-configs {{ tool_registration_repo }}:{{ docker_tag }}
    --config={{ config_path }} --de-database-name={{ de_database_name }}

- name: remove the tool registration config container
  shell: docker rm tool-registration-configs
