---
# dependecies file for docker-cleanup
dependencies:

    - role: cfg-service
      service_name_short: docker-cleanup
      group_name: docker-ready
      src: docker-cleanup/docker-gc-exclude.j2
      dest: /etc/docker-gc-exclude
      tags:
          - docker-cleanup
    - role: cfg-service
      group_name: docker-ready
      service_name_short: docker-cleanup
      src: docker-cleanup/docker-gc-exclude-containers.j2
      dest: /etc/docker-gc-exclude-containers
      tags:
          - docker-cleanup

    - role: cfg-systemd-unit
      group_name: docker-ready
      service_name_short: docker-cleanup
      systemd_enable: false
      tags:
          - docker-cleanup
    - role: cfg-systemd-unit
      group_name: docker-ready
      service_name_short: docker-cleanup
      unit_type: timer
      tags:
          - docker-cleanup

