---
# tasks file for cfg-logging

- debug: msg="Placing {{log_file_name}}"
  tags:
      - logging_config

- name: Place logging config file
  template: src={{src}} dest={{dest}} owner={{owner}} group={{group}} mode=0644
  tags:
      - logging_config
