---
- name: Update de-db database
  hosts: db-proxy:&systems
  tags:
      - de-db
      - databases
  become: False
  roles:
      - { role: de-update-database-de, tags: ["de-db"] }

- name: Update notifications database
  hosts: db-proxy:&systems
  tags:
      - notification-db
      - databases
  become: False
  roles:
      - { role: de-update-database-notifications, tags: ["notification-db"] }

- name: Update metadata database
  hosts: db-proxy:&systems
  tags:
      - metadata-db
      - databases
  become: False
  roles:
      - { role: de-update-database-metadata, tags: ["metadata-db"] }

- name: Update permissions database
  hosts: db-proxy:&systems
  tags:
      - permissions-db
      - databases
  become: False
  roles:
      - { role: de-update-database-permissions, tags: ["permissions-db"] }
