---

- include: TMP-services-cleanup.yaml

- include: services-common.yml

- name: Bring down DE target
  hosts: docker-ready
  sudo: True
  gather_facts: false
  tags:
      - systemd
      - systemd_target
  roles:
      - role: systemd-de-target 
        up: false

  include: systemd-de-target.yaml up=false

- include: rsyslog-config.yaml

- include: deploy-backend.yaml

- include: ui.yaml

- include: amqp-brokers.yaml
  when: not parasitic

- include: deploy-irods-elasticsearch.yaml
  when: not parasitic

- include: systems.yaml
  vars:
    reboot: true

- name: Restart DE target
  hosts: docker-ready
  sudo: True
  gather_facts: false
  tags:
      - systemd
      - systemd_target
  roles:
      - role: systemd-de-target 
        up: true

- include: verify-POST_DEPLOY.yaml

