---
- include: db-migrations.yaml

- include: playbooks/10-iplant-data-cfg.yaml

- include: playbooks/10-logstash-forwarder.yaml

- include: playbooks/10-services-cfg.yaml

- include: elk-stack.yaml

- include: playbooks/10-jex.yaml

- include: playbooks/porklock.yaml

- name: Ensure self-executing jars will run on Condor nodes
  hosts: condor
  sudo: yes
  gather_facts: false
  roles:
      - 01-condor-exec-jar

