# Setup inventories/localhost.cfg and host_vars/localhost as described in
# doc/work_instructions/Local_Configs.md
#
# Supported extra-vars: service="dest-service-name"
#                       de_config_dir="/etc/iplant/de"
#                       config_name="service.properties"
#                       config_template="roles/path-to-role/templates/service.properties.j2"
#                       @local_dev/service.json
#
# This playbook will do funny things with old versions of ansible, due to changes in how variable expansion works. If something weird is happening, probably update your ansible version.
#
# This playbook will write local terrain configs by default.
#
# For example:
# Write local configs for terrain to /etc/iplant/de/terrain.properties.
# ansible-playbook local-service-config.yaml -i inventories/localhost.cfg
#
# Write local configs for data-info to /etc/iplant/de/data-info.properties.
# ansible-playbook local-service-config.yaml -i inventories/localhost.cfg --extra-vars="service=data-info"
---
- hosts: localhost
  vars:
    svce: "{{ service | default('terrain') }}"
    config_template: "roles/util-cfg-service/templates/{{ svce }}.properties.j2"
    config_name: "{{ svce }}.properties"
  tasks:
  - debug: msg="writing {{ config_template }} to {{ de_config_dir }}/{{ config_name }}"
  - name: write local service configs
    local_action: template src="{{ config_template }}" dest="{{ de_config_dir }}/{{ config_name }}" mode=0644
