---
# Updates specified service configs, systemd configs, and pulls service docker images.
# See documentation for `deploy-service-cfg` and `deploy-service-systemd` for 
# more info.
#

- hosts: services
  sudo: yes

  roles:
    - role: deploy-service-cfg
    - role: deploy-service-systemd

