---
# vars:
#   reboot - A boolean used to indicate whether or not the playbook should reboot the servers. It
#            defaults to false.

- hosts: systems
  sudo: true
  tags:
      - systems
  roles:
    - role: notify-chat
      msg: "Updating {{ inventory_hostname }} system packages"

  tasks:
    - group_by: key={{ ansible_distribution }}
      changed_when: false

    - group_by: key={{ ansible_distribution }}_{{ ansible_distribution_major_version }}
      changed_when: false

- hosts: CentOS:RedHat
  gather_facts: false
  sudo: true
  tags:
      - systems
  tasks:
    - name: upgrade system packages
      yum: name=* state=latest

- hosts: CentOS:RedHat:&builders
  gather_facts: false
  sudo: true
  tags:
      - systems
  tasks:
    - name: ensure tomcat owns /usr/src/redhat
      file: path=/usr/src/redhat state=directory owner=tomcat recurse=true

- hosts: CentOS:RedHat:&db
  gather_facts: false
  sudo: true
  tags:
      - systems
  tasks:
    - name: ensure DE DBMS starts on boot
      service: name=postgresql-9.2 enabled=true

- hosts: systems:!CentOS_7
  gather_facts: false
  sudo: true
  tags:
      - systems
  roles:
    - denyhosts

- hosts: systems
  gather_facts: false
  sudo: true
  tags:
      - systems
  pre_tasks:
    - name: reboot server
      when: reboot|default(false)
      command: /sbin/shutdown -r +2

    - name: wait for server to stop
      sudo: false
      when: reboot|default(false)
      local_action: wait_for host="{{ inventory_hostname }}" port={{ ansible_ssh_port }} state=stopped

    - name: verify server up
      sudo: false
      when: reboot|default(false)
      local_action: wait_for host="{{ inventory_hostname }}" port={{ ansible_ssh_port }} state=started

  roles:
    - role: notify-chat
      msg: "Done updating {{ inventory_hostname }} system packages"

