---
- hosts: services
  sudo: True
  vars:
      clean_services:
         - "{{anon_files}}"
         - "{{apps}}"
         - "{{clockwork}}"
         - "{{condor_log_monitor}}"
         - "{{data_info}}"
         - "{{exim}}"
         - "{{iplant_email}}"
         - "{{iplant_groups}}"
         - "{{jexevents}}"
         - "{{kifshare}}"
         - "{{metadata}}"
         - "{{notificationagent}}"
         - "{{saved_searches}}"
         - "{{terrain}}"
         - "{{tree_urls}}"
         - "{{user_preferences}}"
         - "{{user_sessions}}"
      parasitic_services:
         - "{{dewey}}"
         - "{{info_typer}}"
         - "{{infosquito}}"
         - "{{monkey}}"

  roles:
    - role: notify-chat
      msg: "Updating services."

    - jex
    - role: deploy-service-cfg
      services: "{{clean_services}}"
    - role: deploy-service-systemd
      services: "{{clean_services}}"

    - role: deploy-service-cfg
      services: "{{parasitic_services}}"
      when: not parasitic
    - role: deploy-service-systemd
      services: "{{parasitic_services}}"
      when: not parasitic

    - role: notify-chat
      msg: "Done updating services."

