---
# tasks file for elk-kibana

- name: pull elk kibana image
  shell: docker pull {{ elk.kibana.image_name }}
  register: docker_pull_v
  changed_when: docker_pull_v.stdout.find('Image is up to date') == -1
  tags:
      - docker_pull
      - docker_pull_kibana

- name: place Systemd service files
  template: src={{ elk.kibana.service_name }} dest=/usr/lib/systemd/system group=root owner=root mode=0664
  register: service_file_v
  tags:
      - update_service_files
      - update_service_files_kibana

- name: Reload systemd
  shell: systemctl daemon-reload  
  when: service_file_v.changed 
  tags:
      - update_service_files
      - update_service_files_kibana

- name: enable kibana service
  service: name={{elk.kibana.service_name}} enabled={{enable_services}}
  when: service_file_v.changed 
  tags:
      - enable_services
      - enable_kibana

- name: Wait for Elasticsearch to come back
  wait_for: host="{{elk_host}}" port="{{elk.elasticsearch.port}}" state=started
  tags:
      - config
      - config_kibana

- include: visualizations.yaml 
- include: searches.yaml
- include: index-patterns.yaml
- include: dashboards.yaml
