---
# dependecies file for 01-de-target
dependencies:
    - role: cfg-systemd-unit
      group_name: docker-ready
      service_name_short: de
      unit_type: target
      systemd_enable: false
      when: config|bool or config_only|bool
      tags:
          - de-target
