---
# meta/main.yaml for services-common

dependencies:
    - { role: 01-systemd-de-target, when: "'docker-ready' in group_names", config_only: true }
    - { role: 01-systemd-condor-submit-tmp-files, when: "'condor-submission' in group_names" }

