---
# tasks file for services-cleanup-TMP

- include: CORE-7257.yml
- include: CORE-7273.yml
- include: CORE-7307.yml
- include: CORE-7318.yml

- name: Reload systemd
  shell: systemctl daemon-reload  

