---
dependencies:
    - role: cfg-logging
      service_name_short: "{{anon_files.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{anon_files.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{anon_files.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{apps.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{apps.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{apps.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{clockwork.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{clockwork.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{clockwork.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{condor_log_monitor.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{condor_log_monitor.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{condor_log_monitor.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{data_info.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{data_info.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{data_info.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{dewey.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{dewey.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{dewey.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{exim.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{exim.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{exim.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{info_typer.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{info_typer.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{info_typer.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{infosquito.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{infosquito.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{infosquito.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{iplant_email.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{iplant_email.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{iplant_email.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{iplant_groups.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{iplant_groups.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{iplant_groups.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{jexevents.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{jexevents.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{jexevents.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{kifshare.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{kifshare.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{kifshare.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{metadata.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{metadata.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{metadata.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{monkey.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{monkey.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{monkey.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{notificationagent.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{notificationagent.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{notificationagent.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{saved_searches.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{saved_searches.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{saved_searches.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{terrain.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{terrain.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{terrain.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{tree_urls.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{tree_urls.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{tree_urls.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{user_preferences.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{user_preferences.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{user_preferences.service_name_short}}"

    - role: cfg-logging
      service_name_short: "{{user_sessions.service_name_short}}"
    - role: cfg-service
      service_name_short: "{{user_sessions.service_name_short}}"
    - role: cfg-systemd-unit
      service_name_short: "{{user_sessions.service_name_short}}"


