---
# The children of `amqp` are considered exchanges
amqp:
  de:
    name:
    auto_delete: false
    durable: true
    type:

    ## Connection parameters
    scheme: amqp
    user: guest
    password: guest
    host: "{{ groups['amqp-brokers'][0] }}"
    port: 5672
    vhost: /
    # For vhosts containing `/`, use `%2f` instead (e.g. `/my_vhost` => `%2fmy_vhost`
    vhost_encoded:
    mgmt_port:
  irods:
    name: irods
    auto_delete: false
    durable: true
    type: topic

    ## Connection parameters
    scheme: amqp
    user: guest
    password: guest
    host: "{{ groups['irods-amqp-brokers'][0] if groups['irods-amqp-brokers']|count else ''}}"
    port: 5672
    vhost: /
    # For vhosts containing `/`, use `%2f` instead (e.g. `/my_vhost` => `%2fmy_vhost`
    vhost_encoded:
    mgmt_port:

amqp_de_uri: "{{amqp.de.scheme}}://{{amqp.de.user}}:{{amqp.de.password|urlencode}}@{{amqp.de.host}}:{{amqp.de.port}}/{{amqp.de.vhost_encoded}}"
amqp_irods_uri: "{{amqp.irods.scheme}}://{{amqp.irods.user}}:{{amqp.irods.password|urlencode}}@{{amqp.irods.host}}:{{amqp.irods.port}}/{{amqp.irods.vhost_encoded}}"

