---
condor_submission_ip_range:
condor_allow_write: "*.example.org,{{ condor_submission_ip_range }}"
condor:
  host: "{{ groups['condor-master'][0] }}"
  admin: grid@example.org
  collector_name: "{{ environment_name }} pool"
  flock_to:
  filesystem_domain: example.org
  uid_domain: example.org
  allow_write: "{{ condor_allow_write }}"
  allow_read: "{{ condor_allow_write }}"

