---
iplant_email:
  host: "{% if use_overlay %}iplant-email{% else %}{{ groups['iplant-email'][0] }}{% endif %}"
  port:
  base: "http://{% if use_overlay %}iplant-email{% else %}{{ groups['iplant-email'][0] }}{% endif %}"
  service_name: iplant-email.service
  service_name_short: iplant-email
  compose_service: iplant_email
  service_description: iPlant Email service
  image_name: iplant-email
  container_name: iplant-email
  properties_file: iplant-email.properties
  log_file: iplant-email-docker.log
  max_heap: "{{ max_heap.low }}"

