---
kifshare:
  host: "{% if use_overlay %}kifshare{% else %}{{ groups['kifshare'][0] }}{% endif %}"
  port:
  service_name: kifshare.service
  service_name_short: kifshare
  compose_service: kifshare
  service_description: kifshare service
  image_name: kifshare
  container_name: kifshare
  properties_file: kifshare.properties
  log_file: kifshare-docker.log
  mode: prod
  download_buffer_size: 100
  max_heap: "{{ max_heap.low }}"

