---
- name: check if network exists already
  become: true
  shell: "docker network ls -f \"name=de-{{environment_name}}\" --format \"{{ '{{' }} .Name {{ '}}' }}\""
  register: net_exists
 
- name: check if overlay is possible
  become: true
  shell: "docker info -f \"{{ '{{' }} .ClusterStore {{ '}}' }}\""
  register: overlay_possible

# Only make a network if the network doesn't already exist
# Only make it overlay if the daemon supports it (i.e. has a cluster-store configured)
- name: create the docker network for the de
  become: true
  shell: "docker network create --driver {% if use_overlay and overlay_possible.stdout != \"\" %}overlay{% else %}bridge{% endif %} de-{{environment_name}}"
  when: net_exists.stdout == ""
