---
#- name: create the /var/log/de directory
#  file: path={{logging.dir}} owner=root group=root mode=0755 state=directory
#  tags:
#      - config
#
#- name: create the /etc/nginx directory
#  file: path=/etc/nginx owner=iplant group=iplant mode=0755 state=directory
#  tags:
#      - config

- name: pull the nginx-ssl image
  shell: docker pull {{docker.user}}/{{de.http_server.image_name}}:{{docker.tag}}
  register: docker_pull_nginx_v
  changed_when: docker_pull_nginx_v.stdout.find('Image is up to date') == -1
  tags:
      - ui
      - docker_pull

- name: pull the de ui image
  shell: docker pull {{docker.user}}/{{de.image_name}}:{{docker.tag}}
  register: docker_pull_ui_v
  changed_when: docker_pull_ui_v.stdout.find('Image is up to date') == -1
  tags:
      - ui
      - docker_pull

