---
# tasks file for elk-data
- name: pull elk images
  shell: docker pull {{ elk.data.image_name }}
  register: docker_pull_v
  changed_when: docker_pull_v.stdout.find('Image is up to date') == -1
  tags:
      - elk-data
      - docker_pull

- name: restart elk data service
  service: name={{elk.data.service_name}} state=restarted
  ignore_errors: true
  tags:
      - elk-data
      - service_restart
        
