---
# tasks file for systemd-de-target

- name: Bring {{systemd_target}} up (isolate)
  shell: systemctl isolate {{systemd_target}}
  when: up|bool and not config_only|bool
  tags:
      - de-target

- name: Stop {{systemd_target}}
  shell: systemctl isolate {{fallback_target}}
  when: not (config_only|bool or up|bool)
  tags:
      - de-target
  
