- name: ensure /etc/rsyslog.d exists
  sudo: yes
  file: path={{rsyslog_conf_dir}} owner=root group=root mode=0755 state=directory
  tags: 
      - update_service_files

- name: place rsyslog configuration files
  sudo: yes
  template: src=20-iplant.conf dest={{rsyslog_conf_dir}}/20-iplant.conf
  register: config_file_v
  tags:
      - config

- name: Restart rsyslog service
  sudo: yes
  service: name=rsyslog state=restarted
  when: config_file_v.changed
  tags:
      - restart_services
