# Delegates to colored.yaml or uncolored.yaml depending on deploy_use_color.
---

- fail: msg="The service_name variable is required by de-deploy-service."
  when: not service_name

- debug: msg="Deploying {{service_name}}"

- include: "colored.yaml"
  when: deploy_use_color

- include: "uncolored.yaml"
  when: not deploy_use_color
