# Pulls a docker-compose service.
---

- name: pull the {{pull_service_name}} image(s)
  environment:
    DE_TAG: "{{docker.tag}}"
    DE_ENV: "{{environment_name}}"
    HOSTNAME: "{{ hostname_i.stdout_lines[0] }}"
  shell: "docker-compose -f {{docker_compose_path}} pull {{pull_service_name}}"
  register: docker_pull_v
  changed_when: true
  tags:
      - docker_pull
