# Delegates to restart-service.yaml, since uncolored deployment simply restarts the service.
---

- include: check-service.yaml
  vars:
    check_service_name: "{{service_name}}"

- include: check-service.yaml
  vars:
    check_service_name: "config_{{service_name}}"
  when: has_configs|default(true)

- include: check.yaml
  vars:
    check_service_name: "iplant_data_{{service_name}}"
  when: has_iplant_data|default(false)

- include: restart-service.yaml
  vars:
    restart_service_name: "{{service_name}}"
