---
# cron-stats: install cron job
- name: remove previous cron scripts/apps
  file: path="{{ de_config_dir }}/cron" state=absent

- name: create the /etc/iplant/de/cron directory
  file: path="{{ de_config_dir }}/cron" owner=root group=root mode=0755 state=directory

- name: get the dockerHostStats file
  get_url: url={{ dockerHostStats_url }} dest="{{ de_config_dir }}/cron/" owner=root group=root mode=0777

- name: place the shell wrapper 
  template: src=getStats.sh.j2 dest="{{ de_config_dir }}/cron/getStats.sh" owner=root group=root mode=0777

- name: place the system_stats_syslog file
  template: src=system_stats_syslog.j2 dest=/etc/cron.d/system_stats_syslog

