---
# dependecies file for de-ui
dependencies:
    - role: util-cfg-docker-pull-configs
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"
      tags:
          - ui
          - service_config

    - role: util-cfg-docker-pull-configs
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"
      tags:
          - ui
          - service_config

    - role: util-cfg-docker-pull
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"
      tags:
          - ui

    - role: util-cfg-docker-pull
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"
      tags:
          - ui
