---
# tasks file for logrotate.d
- name: Place logrotate file
  sudo: yes
  template: src={{logrotate_file}} dest=/etc/logrotate.d/ group=root owner=root mode=0644
  tags:
      - config
      - logrotate

- name: Force rotate logfiles
  sudo: yes
  shell: logrotate -f /etc/logrotate.d/{{logrotate_file}}
  when: force_rotate
  ignore_errors: yes
  tags:
      - config
      - logrotate
