---
- name: Install Python 2.6
  sudo: yes
  yum: name=python26 state=latest
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "5"
  tags:
    - python

- name: Install python-ssl
  sudo: yes
  yum: name=python-ssl state=latest
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "5"
  tags:
    - python

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "5"
  tags:
    - python

- name: Run get-pip.py
  sudo: yes
  command: python2.6 /tmp/get-pip.py
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "5"
  tags:
    - python

- name: install python-setuptools.noarch
  sudo: yes
  yum: name=python-setuptools.noarch state=latest
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
  tags:
    - python

- name: install pip
  sudo: yes
  command: easy_install pip
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
  tags:
    - python

