galaxy_info:
  author: Dennis Roberts, Paul Sarando
  description: Role to register existing DE tools in the DE permissions database.
  company: CyVerse
  license: BSD

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags: []

dependencies: []
