---
- name: update docker-py
  pip: name="docker-py" state="latest"

- name: pull the app registration docker image
  shell: docker pull {{app_registration_repo}}:{{docker_tag}}

- name: pull the configuration docker image
  shell: docker pull {{config_repo}}:{{docker_tag}}

- name: delete the configuration container if it exists
  shell: docker rm app-registration-configs || echo "nothing to see here, move along"

- name: create the configuration container
  shell: docker create --name app-registration-configs {{config_repo}}:{{docker_tag}}

- name: register existing DE apps
  shell: >-
    docker run --rm --volumes-from app-registration-configs {{ app_registration_repo }}:{{ docker_tag }}
    --config={{ config_path }} --de-database-name={{ de_database_name }}

- name: remove the app registration config container
  shell: docker rm app-registration-configs
