---
- name: ensure elasticsearch has started
  wait_for: port={{ elasticsearch.network_http_port }}

- name: check data index existence
  uri: url={{ data_resource_url }} method=HEAD
  register: result
  failed_when: "result.status != 200 and result.status != 404"

- name: create data index
  when: result.status == 404 
  uri: url={{ data_resource_url }} method=PUT

- name: wait for index allocation
  when: result.status == 404
  uri: url={{ data_resource_url }} method=HEAD
  register: result
  until: result.status != 404
  retries: 1
  delay: 1

- name: close data index
  uri: url={{ data_resource_url }}/_close method=POST

- include: put-cfg.yaml path=_settings file=data.json

- name: open data index
  uri: url={{ data_resource_url }}/_open method=POST

- include: put-cfg.yaml path=file/_mapping file=file.json

- include: put-cfg.yaml path=folder/_mapping file=folder.json

- include: put-cfg.yaml path=tag/_mapping file=tag.json

