---
# dependecies file for support-elk-logstash
dependencies:
    - role: util-cfg-systemd-unit
      group_name: elk
      service_name_short: "{{elk.logstash.service_name_short}}"
      tags:
          - elk-logstash

