---
# tasks file for cfg-docker-pull
#

- debug: msg="Stopping {{service_name}}"
  tags:
      - docker_stop

- name: stop the {{service_name}} image
  environment:
    DE_TAG: "{{docker.tag}}"
    DE_ENV: "{{environment_name}}"
    HOSTNAME: "{{inventory_hostname}}"
  shell: "docker-compose -f {{docker_compose_path}} stop {{service_name}}"
  register: docker_up_v
  changed_when: docker_up_v.stdout.find('Image is up to date') == -1
  tags:
    - docker_stop
