---
- name: create the vhost
  rabbitmq_vhost: 
      name: "{{ amqp.de.vhost }}"
      state: present

- name: set up the user
  rabbitmq_user:
    user: "{{ amqp.de.user }}"
    password: "{{ amqp.de.password }}"
    vhost: "{{ amqp.de.vhost }}"
    state: present
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
