---
# vars file for elk-kibana
elk_host: "{{ groups['elk'][0]}}"
elk_url: "http://{{elk_host}}:{{elk.elasticsearch.port}}"
v1_url: "{{elk_url}}/.kibana/visualization/Top-25-Launched-Apps" 
v2_url: "{{elk_url}}/.kibana/visualization/Top-25-Users-by-App-Submission"
v3_url: "{{elk_url}}/.kibana/visualization/Top-25-Users-by-Login"
v4_url: "{{elk_url}}/.kibana/visualization/Top-25-Users-by-Sharing-Activity"
v5_url: "{{elk_url}}/.kibana/visualization/Errors-by-Service"
v6_url: "{{elk_url}}/.kibana/visualization/Total-Public-App-Submissions"
v7_url: "{{elk_url}}/.kibana/visualization/Total-Public-slash-Private-App-Submissions"
s1_url: "{{elk_url}}/.kibana/search/All-logged-job-submissions"
i0_url: "{{elk_url}}/.kibana/config/{{elk.kibana.version}}"
i1_url: "{{elk_url}}/.kibana/index-pattern/de-logs"
i2_url: "{{elk_url}}/.kibana/index-pattern/de-error-logs"
i3_url: "{{elk_url}}/.kibana/index-pattern/de-metrics"
d1_url: "{{elk_url}}/.kibana/dashboard/Top-25-User-Activity"

