- debug: msg="Pulling config_{{service_name}}"
  tags:
      - docker_pull_configs

- name: pull the config_{{service_name}} image
  environment:
    DE_TAG: "{{docker.tag}}"
    DE_ENV: "{{environment_name}}"
    HOSTNAME: "{{inventory_hostname}}"
  shell: "docker-compose -f {{docker_compose_path}} pull config_{{service_name}}"
  register: docker_pull_v
  changed_when: docker_pull_v.stdout.find('Image is up to date') == -1
  tags:
    - docker_pull_configs
