- name: Configure condor-launcher
  hosts: jex
  become: yes
  gather_facts: false
  any_errors_fatal: true
  tags:
    - condor-launcher
  roles:
    - role: util-notify-chat
      msg: "Deploying condor-launcher"
    - role: de-condor-launcher
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying condor-launcher"
