---
- name: Redeploy clockwork
  hosts: clockwork:&systems
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - services
    - uncolored
    - clockwork
  roles:
    - role: util-notify-chat
      msg: "Deploying clockwork"
    - role: de-deploy-service
      deploy_use_color: false
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{clockwork.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying clockwork"
