---
- name: Redeploy dewey
  hosts: dewey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - uncolored
    - dewey
  roles:
    - role: util-notify-chat
      when: not parasitic
      msg: "Deploying dewey"
    - role: de-deploy-service
      deploy_use_color: false
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      when: not parasitic
      service_name: "{{dewey.compose_service}}"
    - role: util-notify-chat
      when: not parasitic
      msg: ":heavy_check_mark: Done deploying dewey"
