---
- name: Redeploy infosquito
  hosts: infosquito:&systems
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - services
    - uncolored
    - infosquito
  roles:
    - role: util-notify-chat
      when: not parasitic
      msg: "Deploying infosquito"
    - role: de-deploy-service
      deploy_use_color: false
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      when: not parasitic
      service_name: "{{infosquito.compose_service}}"
    - role: util-notify-chat
      when: not parasitic
      msg: ":heavy_check_mark: Done deploying infosquito"
