---
- name: Redeploy monkey
  hosts: monkey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - uncolored
    - monkey
  roles:
    - role: util-notify-chat
      when: not parasitic
      msg: "Deploying monkey"
    - role: de-deploy-service
      deploy_use_color: false
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      when: not parasitic
      service_name: "{{monkey.compose_service}}"
    - role: util-notify-chat
      when: not parasitic
      msg: ":heavy_check_mark: Done deploying monkey"
