---
- name: Redeploy notification-agent
  hosts: notificationagent:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - colored
    - notificationagent
  roles:
    - role: util-notify-chat
      msg: "Deploying notification-agent"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{notificationagent.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying notification-agent"
