---

- name: "Update keys in consul"
  hosts: consul
  run_once: true
  become: true
  gather_facts: false
  tags:
    - consul-kv
  roles:
    - role: de-populate-consul
      cleanup: True
      kv:
        - {key: "configs/{{environment_name}}/amqp/uri", value: "{{ amqp_de_uri }}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/name", value: "{{amqp.de.name}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/type", value: "{{amqp.de.type}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/durable", value: "{{amqp.de.durable}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/auto-delete", value: "{{amqp.de.auto_delete}}"}
        - {key: "configs/{{environment_name}}/irods-amqp/uri", value: "{{amqp_irods_uri}}"}
        - {key: "configs/{{environment_name}}/irods-amqp/exchange/name", value: "{{amqp.irods.name}}"}
        - {key: "configs/{{environment_name}}/de-db/uri", value: "postgresql://{{db_user}}:{{db_password}}@{{db_host}}:{{db_port}}/{{db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/metadata-db/uri", value: "postgresql://{{metadata_db_user}}:{{metadata_db_password}}@{{metadata_db_host}}:{{metadata_db_port}}/{{metadata_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/metadata-db/host", value: "{{ metadata_db_host }}"}
        - {key: "configs/{{environment_name}}/metadata-db/port", value: "{{ metadata_db_port }}"}
        - {key: "configs/{{environment_name}}/metadata-db/name", value: "{{ metadata_db_name }}"}
        - {key: "configs/{{environment_name}}/metadata-db/user", value: "{{ metadata_db_user }}"}
        - {key: "configs/{{environment_name}}/metadata-db/pass", value: "{{ metadata_db_password }}"}
        - {key: "configs/{{environment_name}}/notification-db/uri", value: "postgresql://{{notification_db_user}}:{{notification_db_password}}@{{notification_db_host}}:{{notification_db_port}}/{{notification_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/notification-db/driver", value: "{{ notification_db_driver }}"}
        - {key: "configs/{{environment_name}}/notification-db/subprotocol", value: "{{ notification_db_vendor }}"}
        - {key: "configs/{{environment_name}}/notification-db/host", value: "{{ notification_db_host }}"}
        - {key: "configs/{{environment_name}}/notification-db/port", value: "{{ notification_db_port }}"}
        - {key: "configs/{{environment_name}}/notification-db/name", value: "{{ notification_db_name }}"}
        - {key: "configs/{{environment_name}}/notification-db/user", value: "{{ notification_db_user }}"}
        - {key: "configs/{{environment_name}}/notification-db/pass", value: "{{ notification_db_password }}"}
        - {key: "configs/{{environment_name}}/permissions-db/uri", value: "postgresql://{{permissions_db_user}}:{{permissions_db_password}}@{{permissions_db_host}}:{{permissions_db_port}}/{{permissions_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/grouper-db/uri", value: "postgresql://{{grouper.db.user}}:{{grouper.db.pass}}@{{grouper.db.host}}:{{grouper.db.port}}/{{grouper.db.name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/irods/user", value: "{{irods.user}}"}
        - {key: "configs/{{environment_name}}/irods/pass", value: "{{irods.password}}"}
        - {key: "configs/{{environment_name}}/irods/host", value: "{{irods.host}}"}
        - {key: "configs/{{environment_name}}/irods/port", value: "{{irods.port}}"}
        - {key: "configs/{{environment_name}}/irods/base", value: "{{irods.home}}"}
        - {key: "configs/{{environment_name}}/irods/resc", value: "{{irods.default_resource}}"}
        - {key: "configs/{{environment_name}}/irods/zone", value: "{{irods.zone}}"}
        - {key: "configs/{{environment_name}}/icat/host", value: "{{icat.host}}"}
        - {key: "configs/{{environment_name}}/icat/port", value: "{{icat.port}}"}
        - {key: "configs/{{environment_name}}/icat/user", value: "{{icat.user}}"}
        - {key: "configs/{{environment_name}}/icat/password", value: "{{icat.password}}"}
        - {key: "configs/{{environment_name}}/icat/db", value: "{{icat.db}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/base", value: "http://{{ data_store.elasticsearch.host }}:{{ data_store.elasticsearch.port }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/host", value: "{{ data_store.elasticsearch.host }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/port", value: "{{ data_store.elasticsearch.port }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/data-index", value: "{{ data_store.elasticsearch.data_index }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/data-alias", value: "data"}
        - {key: "configs/{{environment_name}}/elasticsearch/scroll-size", value: "1000"}
        - {key: "configs/{{environment_name}}/elasticsearch/batch-size", value: "1000"}
        - {key: "configs/{{environment_name}}/grouper/base", value: "{{ grouper.ws.base_url }}"}
        - {key: "configs/{{environment_name}}/grouper/api-version", value: "{{ iplant_groups.grouper.api_version }}"}
        - {key: "configs/{{environment_name}}/grouper/user", value: "{{ grouper.admin.user }}"}
        - {key: "configs/{{environment_name}}/grouper/pass", value: "{{ grouper.admin.pass }}"}
        - {key: "configs/{{environment_name}}/porklock/image", value: "discoenv/porklock"}
        - {key: "configs/{{environment_name}}/porklock/tag", value: "{{docker.tag}}"}
        - {key: "configs/{{environment_name}}/smtp/host", value: "local-exim"}
        - {key: "configs/{{environment_name}}/smtp/from-address", value: "{{ email_smtp_from_address }}"}
        - {key: "configs/{{environment_name}}/apps/base", value: "{{apps.base}}"}
        - {key: "configs/{{environment_name}}/apps/de-callback-uri", value: "{{apps.base}}/callbacks/de-job"}
        - {key: "configs/{{environment_name}}/email/base", value: "{{iplant_email.base}}"}
        - {key: "configs/{{environment_name}}/groups/base", value: "{{iplant_groups.base_url}}"}
        - {key: "configs/{{environment_name}}/notifications/base", value: "{{notificationagent.base}}"}
        - {key: "configs/{{environment_name}}/terrain/base", value: "{{terrain.base}}"}
        - {key: "configs/{{environment_name}}/dewey/qos", value: "100"}
        - {key: "configs/{{environment_name}}/info-typer/qos", value: "100"}
        - {key: "configs/{{environment_name}}/monkey/log-progress/enabled", value: "true"}
        - {key: "configs/{{environment_name}}/kifshare/mode", value: "{{ kifshare.mode }}"}
        - {key: "configs/{{environment_name}}/kifshare/download-buffer-size", value: "{{ kifshare.download_buffer_size }}"}
        - {key: "configs/{{environment_name}}/kifshare/footer-text", value: 'CyVerse is funded by a grant from the National Science Foundation Plant Science Cyberinfrastructure Collaborative (#DBI-0735191, #DBI-1265383).'}
        - {key: "configs/{{environment_name}}/kifshare/resources-root", value: "./resources"}
        - {key: "configs/{{environment_name}}/kifshare/images-dir", value: "img"}
        - {key: "configs/{{environment_name}}/kifshare/js-dir", value: "js"}
        - {key: "configs/{{environment_name}}/kifshare/css-dir", value: "css"}
        - {key: "configs/{{environment_name}}/kifshare/flash-dir", value: "flash"}
        - {key: "configs/{{environment_name}}/kifshare/robots-txt", value: "robots.txt"}
        - {key: "configs/{{environment_name}}/kifshare/logo-path", value: "resources/img/cyverse-logo-small.png"}
        - {key: "configs/{{environment_name}}/kifshare/favicon-path", value: "resources/img/cyverse_logo.ico"}
        - {key: "configs/{{environment_name}}/kifshare/client-cache/scope", value: "public"}
        - {key: "configs/{{environment_name}}/kifshare/client-cache/max-age", value: "604800"}
        - {key: "configs/{{environment_name}}/kifshare/irods-url", value: "https://pods.iplantcollaborative.org/wiki/display/start/Using+icommands"}
        - {key: "configs/{{environment_name}}/kifshare/flags/de-import", value: "\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}"}
        - {key: "configs/{{environment_name}}/kifshare/flags/curl", value: "curl -o \'\\{\\{filename\\}\\}\' \'\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/flags/wget", value: "wget \'\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/flags/iget", value: "iget -t \\{\\{ticket-id\\}\\} \'\\{\\{abspath\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/css-files", value: "resources/css/reset.css,resources/css/960.css,resources/css/kif.css"}
        - {key: "configs/{{environment_name}}/kifshare/javascript-files", value: "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js,https://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.0/mustache.min.js,resources/js/json2.js,resources/js/kif.js"}
        - {key: "configs/{{environment_name}}/de/base", value: "{{ de.base }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/age", value: "{{ tree_urls.cleanup_age }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/start", value: "{{ tree_urls.cleanup_start }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/enable", value: "{{ tree_urls.cleanup_enable }}"}
        - {key: "configs/{{environment_name}}/tree-urls/avu", value: "{{ tree_urls.avu }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/start", value: "{{ notificationagent.clean_start }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/age", value: "{{ notificationagent.clean_age }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/enable", value: "{{ notificationagent.clean_enable }}"}
        - {key: "configs/{{environment_name}}/services/port", value: "{{ default_service_port }}"}
        - {key: "configs/{{environment_name}}/infosquito/notify-enabled", value: "{{ infosquito.notify_enabled }}"}
        - {key: "configs/{{environment_name}}/infosquito/notify-count", value: "{{ infosquito.notify_count }}"}
        - {key: "configs/{{environment_name}}/infosquito/retry-interval", value: "{{ infosquito.retry_interval }}"}
        - {key: "configs/{{environment_name}}/infosquito/reindex-queue", value: "{{ infosquito.reindex_queue }}"}
