---
- name: Redeploy permissions
  hosts: permissions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - colored
    - permissions
  roles:
    - role: util-notify-chat
      msg: "Deploying permissions"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{permissions.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying permissions"
