---
# - name: Update iplant-data
#   hosts: docker-ready
#   sudo: true
#   gather_facts: false
#   tags:
#     - services
#     - iplant-data
#   roles:
#     - role: util-cfg-docker-pull
#       service_name: "{{data_container.compose_service}}"
#       service_name_short: "{{data_container.service_name_short}}"

- name: Update anon-files
  hosts: anon-files
  sudo: true
  gather_facts: false
  tags:
    - services
    - anon-files
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"

    - role: util-cfg-docker-pull
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"

- name: Update apps
  hosts: apps
  sudo: true
  gather_facts: false
  tags:
    - services
    - apps
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"

- name: Update iplant-data-apps
  hosts: docker-ready
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-data
  roles:
    - role: util-cfg-docker-pull
      service_name: "iplant_data_{{apps.compose_service}}"
      service_name_short: "iplant_data_{{apps.service_name_short}}"

- name: Update clockwork
  hosts: clockwork
  sudo: true
  gather_facts: false
  tags:
    - services
    - clockwork
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"

- name: Update data-info
  hosts: data-info
  sudo: true
  gather_facts: false
  tags:
    - services
    - data-info
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"

- name: Update dewey
  hosts: dewey
  sudo: true
  gather_facts: false
  tags:
    - services
    - dewey
  roles:
    - role: util-cfg-docker-pull-configs
      when: not parasitic
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"
    - role: util-cfg-docker-pull
      when: not parasitic
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"

- name: Update de-ui
  hosts: ui
  sudo: true
  gather_facts: false
  tags:
    - ui
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"

- name: Update iplant-data-de-ui
  hosts: docker-ready
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-data
  roles:
    - role: util-cfg-docker-pull
      service_name: "iplant_data_{{de.compose_service}}"
      service_name_short: "iplant_data_{{de.service_name_short}}"

- name: Update de-ui-nginx
  hosts: ui
  sudo: true
  gather_facts: false
  tags:
    - ui
    - de-ui-nginx
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"

- name: Update iplant-data-de-ui-nginx
  hosts: docker-ready
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-data
  roles:
    - role: util-cfg-docker-pull
      service_name: "iplant_data_{{de.http_server.compose_service}}"
      service_name_short: "iplant_data_{{de.http_server.service_name_short}}"

- name: Update exim-sender
  hosts: exim-sender
  sudo: true
  gather_facts: false
  tags:
    - services
    - exim-sender
  roles:
    - role: util-cfg-docker-pull
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"

- name: Update info-typer
  hosts: info-typer
  sudo: true
  gather_facts: false
  tags:
    - services
    - info-typer
  roles:
    - role: util-cfg-docker-pull-configs
      when: not parasitic
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"
    - role: util-cfg-docker-pull
      when: not parasitic
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"

- name: Update infosquito
  hosts: infosquito
  sudo: true
  gather_facts: false
  tags:
    - services
    - infosquito
  roles:
    - role: util-cfg-docker-pull-configs
      when: not parasitic
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"
    - role: util-cfg-docker-pull
      when: not parasitic
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"

- name: Update iplant-email
  hosts: iplant-email
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-email
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"

- name: Update iplant-groups
  hosts: iplant-groups
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-groups
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"

- name: Update jobservices
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - jobservices
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: job_status_recorder
      service_name_short: job_status_recorder
    - role: util-cfg-docker-pull-configs
      service_name: jex_adapter
      service_name_short: jex_adapter
    - role: util-cfg-docker-pull
      service_name: jobservices
      service_name_short: jobservices

- name: Update kifshare
  hosts: kifshare
  sudo: true
  gather_facts: false
  tags:
    - services
    - kifshare
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"

- name: Update metadata
  hosts: metadata
  sudo: true
  gather_facts: false
  tags:
    - services
    - metadata
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"

- name: Update monkey
  hosts: monkey
  sudo: true
  gather_facts: false
  tags:
    - services
    - monkey
  roles:
    - role: util-cfg-docker-pull-configs
      when: not parasitic
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"
    - role: util-cfg-docker-pull
      when: not parasitic
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"

- name: Update notification-agent
  hosts: notificationagent
  sudo: true
  gather_facts: false
  tags:
    - services
    - notificationagent
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"

- name: Update saved-searches
  hosts: saved-searches
  sudo: true
  gather_facts: false
  tags:
    - services
    - saved-searches
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"

- name: Update terrain
  hosts: terrain
  sudo: true
  gather_facts: false
  tags:
    - services
    - terrain
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"

- name: Update iplant-data-terrain
  hosts: docker-ready
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-data
  roles:
    - role: util-cfg-docker-pull
      service_name: "iplant_data_{{terrain.compose_service}}"
      service_name_short: "iplant_data_{{terrain.service_name_short}}"

- name: Update tree-urls
  hosts: tree-urls
  sudo: true
  gather_facts: false
  tags:
    - services
    - tree-urls
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"

- name: Update user-preferences
  hosts: user-preferences
  sudo: true
  gather_facts: false
  tags:
    - services
    - user-preferences
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"

- name: Update user-sessions
  hosts: user-sessions
  sudo: true
  gather_facts: false
  tags:
    - services
    - user-sessions
  roles:
    - role: util-cfg-docker-pull-configs
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
    - role: util-cfg-docker-pull
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
