---

- name: "Update keys in consul"
  hosts: consul
  run_once: true
  become: true
  gather_facts: false
  tags:
    - consul-kv
  roles:
    - role: de-populate-consul
      cleanup: True
      kv:
        - {key: "configs/{{environment_name}}/amqp/uri", value: "{{ amqp_de_uri }}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/name", value: "{{amqp.de.name}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/type", value: "{{amqp.de.type}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/durable", value: "{{amqp.de.durable}}"}
        - {key: "configs/{{environment_name}}/amqp/exchange/auto-delete", value: "{{amqp.de.auto_delete}}"}
        - {key: "configs/{{environment_name}}/irods-amqp/uri", value: "{{amqp_irods_uri}}"}
        - {key: "configs/{{environment_name}}/irods-amqp/exchange/name", value: "{{amqp.irods.name}}"}
        - {key: "configs/{{environment_name}}/de-db/uri", value: "postgresql://{{db_user}}:{{db_password}}@{{db_host}}:{{db_port}}/{{db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/metadata-db/uri", value: "postgresql://{{metadata_db_user}}:{{metadata_db_password}}@{{metadata_db_host}}:{{metadata_db_port}}/{{metadata_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/metadata-db/host", value: "{{ metadata_db_host }}"}
        - {key: "configs/{{environment_name}}/metadata-db/port", value: "{{ metadata_db_port }}"}
        - {key: "configs/{{environment_name}}/metadata-db/name", value: "{{ metadata_db_name }}"}
        - {key: "configs/{{environment_name}}/metadata-db/user", value: "{{ metadata_db_user }}"}
        - {key: "configs/{{environment_name}}/metadata-db/pass", value: "{{ metadata_db_password }}"}
        - {key: "configs/{{environment_name}}/notification-db/uri", value: "postgresql://{{notification_db_user}}:{{notification_db_password}}@{{notification_db_host}}:{{notification_db_port}}/{{notification_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/notification-db/driver", value: "{{ notification_db_driver }}"}
        - {key: "configs/{{environment_name}}/notification-db/subprotocol", value: "{{ notification_db_vendor }}"}
        - {key: "configs/{{environment_name}}/notification-db/host", value: "{{ notification_db_host }}"}
        - {key: "configs/{{environment_name}}/notification-db/port", value: "{{ notification_db_port }}"}
        - {key: "configs/{{environment_name}}/notification-db/name", value: "{{ notification_db_name }}"}
        - {key: "configs/{{environment_name}}/notification-db/user", value: "{{ notification_db_user }}"}
        - {key: "configs/{{environment_name}}/notification-db/pass", value: "{{ notification_db_password }}"}
        - {key: "configs/{{environment_name}}/permissions-db/uri", value: "postgresql://{{permissions_db_user}}:{{permissions_db_password}}@{{permissions_db_host}}:{{permissions_db_port}}/{{permissions_db_name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/grouper-db/uri", value: "postgresql://{{grouper.db.user}}:{{grouper.db.pass}}@{{grouper.db.host}}:{{grouper.db.port}}/{{grouper.db.name}}?sslmode=disable"}
        - {key: "configs/{{environment_name}}/irods/user", value: "{{irods.user}}"}
        - {key: "configs/{{environment_name}}/irods/pass", value: "{{irods.password}}"}
        - {key: "configs/{{environment_name}}/irods/host", value: "{{irods.host}}"}
        - {key: "configs/{{environment_name}}/irods/port", value: "{{irods.port}}"}
        - {key: "configs/{{environment_name}}/irods/base", value: "{{irods.home}}"}
        - {key: "configs/{{environment_name}}/irods/resc", value: "{{irods.default_resource}}"}
        - {key: "configs/{{environment_name}}/irods/zone", value: "{{irods.zone}}"}
        - {key: "configs/{{environment_name}}/icat/host", value: "{{icat.host}}"}
        - {key: "configs/{{environment_name}}/icat/port", value: "{{icat.port}}"}
        - {key: "configs/{{environment_name}}/icat/user", value: "{{icat.user}}"}
        - {key: "configs/{{environment_name}}/icat/password", value: "{{icat.password}}"}
        - {key: "configs/{{environment_name}}/icat/db", value: "{{icat.db}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/base", value: "{{elasticsearch_uri}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/uri", value: "{{elasticsearch_uri}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/host", value: "{{ elasticsearch.host }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/port", value: "{{ elasticsearch.port }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/data-index", value: "{{ elasticsearch.indices.data.name }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/data-alias", value: "{{elasticsearch.indices.data.alias}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/indices/data/name", value: "{{ elasticsearch.indices.data.name }}"}
        - {key: "configs/{{environment_name}}/elasticsearch/indices/data/alias", value: "{{elasticsearch.indices.data.alias}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/scroll-size", value: "{{elasticsearch.scroll_size}}"}
        - {key: "configs/{{environment_name}}/elasticsearch/batch-size", value: "{{elasticseach.batch_size}}"}
        - {key: "configs/{{environment_name}}/grouper/base", value: "{{ grouper.ws.base_url }}"}
        - {key: "configs/{{environment_name}}/grouper/api-version", value: "{{ iplant_groups.grouper.api_version }}"}
        - {key: "configs/{{environment_name}}/grouper/user", value: "{{ grouper.admin.user }}"}
        - {key: "configs/{{environment_name}}/grouper/pass", value: "{{ grouper.admin.pass }}"}
        - {key: "configs/{{environment_name}}/porklock/image", value: "discoenv/porklock"}
        - {key: "configs/{{environment_name}}/porklock/tag", value: "{{docker.tag}}"}
        - {key: "configs/{{environment_name}}/smtp/host", value: "local-exim"}
        - {key: "configs/{{environment_name}}/smtp/from-address", value: "{{ email_smtp_from_address }}"}
        - {key: "configs/{{environment_name}}/apps/base", value: "{{apps.base}}"}
        - {key: "configs/{{environment_name}}/apps/de-callback-uri", value: "{{apps.base}}/callbacks/de-job"}
        - {key: "configs/{{environment_name}}/email/base", value: "{{iplant_email.base}}"}
        - {key: "configs/{{environment_name}}/groups/base", value: "{{iplant_groups.base_url}}"}
        - {key: "configs/{{environment_name}}/notifications/base", value: "{{notificationagent.base}}"}
        - {key: "configs/{{environment_name}}/terrain/base", value: "{{terrain.base}}"}
        - {key: "configs/{{environment_name}}/dewey/qos", value: "100"}
        - {key: "configs/{{environment_name}}/info-typer/qos", value: "100"}
        - {key: "configs/{{environment_name}}/monkey/log-progress/enabled", value: "true"}
        - {key: "configs/{{environment_name}}/kifshare/mode", value: "{{ kifshare.mode }}"}
        - {key: "configs/{{environment_name}}/kifshare/download-buffer-size", value: "{{ kifshare.download_buffer_size }}"}
        - {key: "configs/{{environment_name}}/kifshare/footer-text", value: 'CyVerse is funded by a grant from the National Science Foundation Plant Science Cyberinfrastructure Collaborative (#DBI-0735191, #DBI-1265383).'}
        - {key: "configs/{{environment_name}}/kifshare/resources-root", value: "./resources"}
        - {key: "configs/{{environment_name}}/kifshare/images-dir", value: "img"}
        - {key: "configs/{{environment_name}}/kifshare/js-dir", value: "js"}
        - {key: "configs/{{environment_name}}/kifshare/css-dir", value: "css"}
        - {key: "configs/{{environment_name}}/kifshare/flash-dir", value: "flash"}
        - {key: "configs/{{environment_name}}/kifshare/robots-txt", value: "robots.txt"}
        - {key: "configs/{{environment_name}}/kifshare/logo-path", value: "resources/img/cyverse-logo-small.png"}
        - {key: "configs/{{environment_name}}/kifshare/favicon-path", value: "resources/img/cyverse_logo.ico"}
        - {key: "configs/{{environment_name}}/kifshare/client-cache/scope", value: "public"}
        - {key: "configs/{{environment_name}}/kifshare/client-cache/max-age", value: "604800"}
        - {key: "configs/{{environment_name}}/kifshare/irods-url", value: "https://pods.iplantcollaborative.org/wiki/display/start/Using+icommands"}
        - {key: "configs/{{environment_name}}/kifshare/flags/de-import", value: "\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}"}
        - {key: "configs/{{environment_name}}/kifshare/flags/curl", value: "curl -o \'\\{\\{filename\\}\\}\' \'\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/flags/wget", value: "wget \'\\{\\{url\\}\\}/d/\\{\\{ticket-id\\}\\}/\\{\\{filename\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/flags/iget", value: "iget -t \\{\\{ticket-id\\}\\} \'\\{\\{abspath\\}\\}\'"}
        - {key: "configs/{{environment_name}}/kifshare/css-files", value: "resources/css/reset.css,resources/css/960.css,resources/css/kif.css"}
        - {key: "configs/{{environment_name}}/kifshare/javascript-files", value: "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js,https://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.0/mustache.min.js,resources/js/json2.js,resources/js/kif.js"}
        - {key: "configs/{{environment_name}}/de/base", value: "{{ de.base }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/age", value: "{{ tree_urls.cleanup_age }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/start", value: "{{ tree_urls.cleanup_start }}"}
        - {key: "configs/{{environment_name}}/tree-urls/cleanup/enable", value: "{{ tree_urls.cleanup_enable }}"}
        - {key: "configs/{{environment_name}}/tree-urls/avu", value: "{{ tree_urls.avu }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/start", value: "{{ notificationagent.clean_start }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/age", value: "{{ notificationagent.clean_age }}"}
        - {key: "configs/{{environment_name}}/notification-agent/clean/enable", value: "{{ notificationagent.clean_enable }}"}
        - {key: "configs/{{environment_name}}/services/port", value: "{{ default_service_port }}"}
        - {key: "configs/{{environment_name}}/infosquito/notify-enabled", value: "{{ infosquito.notify_enabled }}"}
        - {key: "configs/{{environment_name}}/infosquito/notify-count", value: "{{ infosquito.notify_count }}"}
        - {key: "configs/{{environment_name}}/infosquito/retry-interval", value: "{{ infosquito.retry_interval }}"}
        - {key: "configs/{{environment_name}}/infosquito/reindex-queue", value: "{{ infosquito.reindex_queue }}"}
        - {key: "configs/{{environment_name}}/de/default-build-number", value: "{{ de_version_name }}"}
        - {key: "configs/{{environment_name}}/de/release-version", value: "{{ de_version }}"}
        - {key: "configs/{{environment_name}}/de/base-url", value: "{{ cas_base }}"}
        - {key: "configs/{{environment_name}}/de/cas-server-name", value: "{{ de.app_base }}"}
        - {key: "configs/{{environment_name}}/de/cas-validation", value: "/iplant-cas-ticket-validator"}
        - {key: "configs/{{environment_name}}/de/cas-logout-url", value: "/iplant-cas-logout"}
        - {key: "configs/{{environment_name}}/de/cas-app-name", value: "{{ de.description }}"}
        - {key: "configs/{{environment_name}}/de/cas-login-url", value: "/login"}
        - {key: "configs/{{environment_name}}/de/authorized-groups", value: "{{ admin_groups }}"}
        - {key: "configs/{{environment_name}}/de/group-attribute-name", value: "{{ cas_group_attribute }}"}
        - {key: "configs/{{environment_name}}/de/cas-no-logout-url", value: "{{ cas_no_logout_url }}"}
        - {key: "configs/{{environment_name}}/de/cas-app-list", value: "{{ cas_app_list }}"}
        - {key: "configs/{{environment_name}}/de/keepalive-service", value: "{{ de.app_base }}/de/{{ de.rpc_name }}/{{ de.empty_url }}"}
        - {key: "configs/{{environment_name}}/de/keepalive-target", value: "{{ cas_base }}/login?service={{ de.app_base }}/de/{{ de.rpc_name }}/{{ de.empty_url }}"}
        - {key: "configs/{{environment_name}}/de/keepalive-interval", value: "90"}
        - {key: "configs/{{environment_name}}/jwt/private-key-path", value: "{{ jwt.signing_key.private }}"}
        - {key: "configs/{{environment_name}}/jwt/private-key-password", value: "{{ jwt.signing_key.password }}"}
        - {key: "configs/{{environment_name}}/de/twitter-url", value: "https://twitter.com/cyverseorg"}
        - {key: "configs/{{environment_name}}/de/facebook-url", value: "https://www.facebook.com/CyVerse.org/"}
        - {key: "configs/{{environment_name}}/de/newsletter-url", value: "http://www.cyverse.org/newsletter"}
        - {key: "configs/{{environment_name}}/de/ask-url", value: "http://www.cyverse.org/learning-center/ask-cyverse"}
        - {key: "configs/{{environment_name}}/de/prefix", value: "org.iplantc.services"}
        - {key: "configs/{{environment_name}}/de/rpc-prefix", value: "discoveryenvironment/deservice"}
        - {key: "configs/{{environment_name}}/de/file-identifier", value: "{{ path_list_file_identifier }}"}
        - {key: "configs/{{environment_name}}/de/root-app-category", value: "{{ apps.user_root }}"}
        - {key: "configs/{{environment_name}}/de/default-app-categories", value: "{{ apps.user_subs | string }}"}
        - {key: "configs/{{environment_name}}/de/default-beta-app-category", value: "{{ apps.beta_category }}"}
        - {key: "configs/{{environment_name}}/de/default-hpc-app-category", value: "{{ apps.hpc_category }}"}
        - {key: "configs/{{environment_name}}/de/default-trash-app-category", value: "ffffffff-ffff-ffff-ffff-ffffffffffff"}
        - {key: "configs/{{environment_name}}/de/ontology-attributes", value: "{\"http://edamontology.org/operation.*\":\"rdf:type\",\"http://edamontology.org/topic.*\":\"http://edamontology.org/has_topic\"}"}
        - {key: "configs/{{environment_name}}/de/beta-attr-iri", value: "{{ apps.beta_attr_iri }}"}
        - {key: "configs/{{environment_name}}/de/beta-attr-label", value: "{{ apps.beta_attr_label }}"}
        - {key: "configs/{{environment_name}}/de/beta-value", value: "{{ apps.beta_value }}"}
        - {key: "configs/{{environment_name}}/de/beta-unit", value: "attr"}
        - {key: "configs/{{environment_name}}/de/card-url", value: "https://www.gravatar.com/avatar/"}
        - {key: "configs/{{environment_name}}/de/card-url-options", value: "?d=identicon&s=60"}
        - {key: "configs/{{environment_name}}/de/context-menu-enabled", value: "{{ de.context_menu_enabled }}"}
        - {key: "configs/{{environment_name}}/de/community-data-path", value: "/{{ irods.zone }}/{{ irods.community_data_path }}"}
        - {key: "configs/{{environment_name}}/de/irods-home", value: "{{ irods.home }}"}
        - {key: "configs/{{environment_name}}/de/trash-path", value: "/{{ irods.zone }}/{{ irods.trash_path }}/{{ irods.user }}"}
        - {key: "configs/{{environment_name}}/de/maintenance-file", value: "{{ de.maintenance_file }}"}
        - {key: "configs/{{environment_name}}/de/local-ip-ranges", value: "{{ de.local_ip_ranges }}"}
        - {key: "configs/{{environment_name}}/de/environment-name", value: "{{ environment_name }}"}
        - {key: "configs/{{environment_name}}/de/prod-deployment", value: "{{ prod_deployment }}"}
        - {key: "configs/{{environment_name}}/de/poll-interval", value: "{{ de.notification_poll }}"}
        - {key: "configs/{{environment_name}}/de/support-user", value: "siuser"}
