- name: Configure road-runner
  hosts: condor:jex
  become: yes
  gather_facts: false
  tags:
    - road-runner
  roles:
    - role: util-notify-chat
      msg: "Deploying road-runner"
    - role: de-road-runner
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying road-runner"
