---
# - name: Remove iplant-data
#   hosts: docker-ready
#   sudo: true
#   gather_facts: false
#   tags:
#     - services
#     - iplant-data
#   roles:
#     - role: util-cfg-docker-rm
#       ignore_errors: yes
#       service_name: "{{data_container.compose_service}}"
#       service_name_short: "{{data_container.service_name_short}}"

- name: Remove anon-files
  hosts: anon-files
  sudo: true
  gather_facts: false
  tags:
    - services
    - anon-files
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{anon_files.compose_service}}"
      service_name_short: "{{anon_files.service_name_short}}"
  post_tasks:
    - name: annihilate anon-files
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{anon_files.service_name_short}}

- name: Remove apps
  hosts: apps
  sudo: true
  gather_facts: false
  tags:
    - services
    - apps
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{apps.compose_service}}"
      service_name_short: "{{apps.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "iplant_data_{{apps.compose_service}}"
      service_name_short: "iplant_data_{{apps.compose_service}}"
  post_tasks:
    - name: annihilate apps
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{apps.service_name_short}}

- name: Remove clockwork
  hosts: clockwork
  sudo: true
  gather_facts: false
  tags:
    - services
    - clockwork
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"
  post_tasks:
    - name: annihilate clockwork
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{clockwork.service_name_short}}

- name: Remove clm
  hosts: condor-log-monitor
  sudo: true
  gather_facts: false
  tags:
    - services
    - condor-log-monitor
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{condor_log_monitor.compose_service}}"
      service_name_short: "{{condor_log_monitor.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{condor_log_monitor.compose_service}}"
      service_name_short: "{{condor_log_monitor.service_name_short}}"
  post_tasks:
    - name: annihilate clm
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{condor_log_monitor.service_name_short}}
    - name: annihilate clm part 2
      ignore_errors: yes
      sudo: true
      shell: docker rm -v clm

- name: Remove data-info
  hosts: data-info
  sudo: true
  gather_facts: false
  tags:
    - services
    - data-info
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{data_info.compose_service}}"
      service_name_short: "{{data_info.service_name_short}}"
  post_tasks:
    - name: annihilate data-info
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{data_info.service_name_short}}

- name: Remove dewey
  hosts: dewey
  sudo: true
  gather_facts: false
  tags:
    - services
    - dewey
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"
  post_tasks:
    - name: annihilate dewey
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{dewey.service_name_short}}

- name: Remove de-ui
  hosts: ui
  sudo: true
  gather_facts: false
  tags:
    - ui
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "iplant_data_{{de.compose_service}}"
      service_name_short: "iplant_data_{{de.service_name_short}}"
  post_tasks:
    - name: annihilate de-ui
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{de.service_name_short}}

- name: Remove de-ui-nginx
  hosts: ui
  sudo: true
  gather_facts: false
  tags:
    - ui
    - de-ui-nginx
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "iplant_data_{{de.http_server.compose_service}}"
      service_name_short: "iplant_data_{{de.http_server.service_name_short}}"
  post_tasks:
    - name: annihilate de-ui-nginx
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{de.http_server.service_name_short}}

- name: Remove exim-sender
  hosts: exim-sender
  sudo: true
  gather_facts: false
  tags:
    - services
    - exim-sender
  roles:
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"
  post_tasks:
    - name: annihilate exim-sender
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{exim.service_name_short}}
    - name: annihilate exim-sender part 2
      ignore_errors: yes
      sudo: true
      shell: docker rm -v exim

- name: Remove info-typer
  hosts: info-typer
  sudo: true
  gather_facts: false
  tags:
    - services
    - info-typer
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"
  post_tasks:
    - name: annihilate info-typer
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{info_typer.service_name_short}}

- name: Remove infosquito
  hosts: infosquito
  sudo: true
  gather_facts: false
  tags:
    - services
    - infosquito
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"
  post_tasks:
    - name: annihilate infosquito
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{infosquito.service_name_short}}

- name: Remove iplant-email
  hosts: iplant-email
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-email
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{iplant_email.compose_service}}"
      service_name_short: "{{iplant_email.service_name_short}}"
  post_tasks:
    - name: annihilate iplant-email
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{iplant_email.service_name_short}}

- name: Remove iplant-groups
  hosts: iplant-groups
  sudo: true
  gather_facts: false
  tags:
    - services
    - iplant-groups
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{iplant_groups.compose_service}}"
      service_name_short: "{{iplant_groups.service_name_short}}"
  post_tasks:
    - name: annihilate iplant-groups
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{iplant_groups.service_name_short}}

- name: Remove jex-events
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - jexevents
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{jexevents.compose_service}}"
      service_name_short: "{{jexevents.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{jexevents.compose_service}}"
      service_name_short: "{{jexevents.service_name_short}}"
  post_tasks:
    - name: annihilate jex-events
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{jexevents.service_name_short}}
    - name: annihilate jex-events part 2
      ingore_errors: yes
      sudo: true
      shell: docker rm -v jex-events

- name: Remove kifshare
  hosts: kifshare
  sudo: true
  gather_facts: false
  tags:
    - services
    - kifshare
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{kifshare.compose_service}}"
      service_name_short: "{{kifshare.service_name_short}}"
  post_tasks:
    - name: annihilate kifshare
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{kifshare.service_name_short}}

- name: Remove metadata
  hosts: metadata
  sudo: true
  gather_facts: false
  tags:
    - services
    - metadata
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{metadata.compose_service}}"
      service_name_short: "{{metadata.service_name_short}}"
  post_tasks:
    - name: annihilate metadata
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{metadata.service_name_short}}

- name: Remove monkey
  hosts: monkey
  sudo: true
  gather_facts: false
  tags:
    - services
    - monkey
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"
  post_tasks:
    - name: annihilate monkey
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{monkey.service_name_short}}

- name: Remove notification-agent
  hosts: notificationagent
  sudo: true
  gather_facts: false
  tags:
    - services
    - notificationagent
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{notificationagent.compose_service}}"
      service_name_short: "{{notificationagent.service_name_short}}"
  post_tasks:
    - name: annihilate notificationagent
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{notificationagent.service_name_short}}

- name: Remove saved-searches
  hosts: saved-searches
  sudo: true
  gather_facts: false
  tags:
    - services
    - saved-searches
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{saved_searches.compose_service}}"
      service_name_short: "{{saved_searches.service_name_short}}"
  post_tasks:
    - name: annihilate saved-searches
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{saved_searches.service_name_short}}

- name: Remove terrain
  hosts: terrain
  sudo: true
  gather_facts: false
  tags:
    - services
    - terrain
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{terrain.compose_service}}"
      service_name_short: "{{terrain.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "iplant_data_{{terrain.compose_service}}"
      service_name_short: "iplant_data_{{terrain.service_name_short}}"
  post_tasks:
    - name: annihilate terrain
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{terrain.service_name_short}}

- name: Remove tree-urls
  hosts: tree-urls
  sudo: true
  gather_facts: false
  tags:
    - services
    - tree-urls
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{tree_urls.compose_service}}"
      service_name_short: "{{tree_urls.service_name_short}}"
  post_tasks:
    - name: annihilate tree-urls
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{tree_urls.service_name_short}}

- name: Remove user-preferences
  hosts: user-preferences
  sudo: true
  gather_facts: false
  tags:
    - services
    - user-preferences
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{user_preferences.compose_service}}"
      service_name_short: "{{user_preferences.service_name_short}}"
  post_tasks:
    - name: annihilate user-preferences
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{user_preferences.service_name_short}}

- name: Remove user-sessions
  hosts: user-sessions
  sudo: true
  gather_facts: false
  tags:
    - services
    - user-sessions
  roles:
    - role: util-cfg-docker-rm-configs
      ignore_errors: yes
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
    - role: util-cfg-docker-rm
      ignore_errors: yes
      service_name: "{{user_sessions.compose_service}}"
      service_name_short: "{{user_sessions.service_name_short}}"
  post_tasks:
    - name: annihilate user-sessions
      ignore_errors: yes
      sudo: true
      shell: docker rm -v {{user_sessions.service_name_short}}
