---
# ansible-playbook -K services-common.yaml

- name: Perform common systems configuration
  hosts: systems
  sudo: yes
  gather_facts: false
  tags:
      - config
  roles:
      - services-common
