---
- name: Start clockwork
  hosts: clockwork:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - clockwork
  roles:
    - role: util-cfg-docker-up
      service_name: "{{clockwork.compose_service}}"
      service_name_short: "{{clockwork.service_name_short}}"

- name: Start dewey
  hosts: dewey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - dewey
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{dewey.compose_service}}"
      service_name_short: "{{dewey.service_name_short}}"

- name: Start de-ui
  hosts: ui:&systems
  become: true
  gather_facts: false
  tags:
    - ui
  roles:
    - role: util-cfg-docker-up
      service_name: "{{de.compose_service}}"
      service_name_short: "{{de.service_name_short}}"

- name: Start de-ui-nginx
  hosts: ui:&systems
  become: true
  gather_facts: false
  tags:
    - ui
    - de-ui-nginx
  roles:
    - role: util-cfg-docker-up
      service_name: "{{de.http_server.compose_service}}"
      service_name_short: "{{de.http_server.service_name_short}}"

- name: Start exim-sender
  hosts: exim-sender:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - exim-sender
  roles:
    - role: util-cfg-docker-up
      service_name: "{{exim.compose_service}}"
      service_name_short: "{{exim.service_name_short}}"

- name: Start info-typer
  hosts: info-typer:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - info-typer
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{info_typer.compose_service}}"
      service_name_short: "{{info_typer.service_name_short}}"

- name: Start infosquito
  hosts: infosquito:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - infosquito
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{infosquito.compose_service}}"
      service_name_short: "{{infosquito.service_name_short}}"

- name: Start job-status-to-apps-adapter
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - job-status-to-apps-adapter
  roles:
    - role: util-cfg-docker-up
      service_name: job_status_to_apps_adapter
      service_name_short: job_status_to_apps_adapter

- name: Start job-status-recorder
  hosts: jexevents
  sudo: true
  gather_facts: false
  tags:
    - services
    - job-status-recorder
  roles:
    - role: util-cfg-docker-up
      service_name: job_status_recorder
      service_name_short: job_status_recorder

- name: Start monkey
  hosts: monkey:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - monkey
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{monkey.compose_service}}"
      service_name_short: "{{monkey.service_name_short}}"

- name: Start templeton-periodic
  hosts: templeton-periodic:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - templeton
    - templeton-periodic
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{templeton_periodic.compose_service}}"
      service_name_short: "{{templeton_periodic.service_name_short}}"

- name: Start templeton-incremental
  hosts: templeton-incremental:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - templeton
    - templeton-incremental
  roles:
    - role: util-cfg-docker-up
      when: not parasitic
      service_name: "{{templeton_incremental.compose_service}}"
      service_name_short: "{{templeton_incremental.service_name_short}}"
