---
- name: Stop clm
  hosts: condor-log-monitor:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - condor-log-monitor
  post_tasks:
    - name: remove clm
      ignore_errors: yes
      become: yes
      shell: docker kill clm

- name: Stop jex-events
  hosts: jexevents:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - jexevents
  post_tasks:
    - name: stop jex-events
      ignore_errors: yes
      become: true
      shell: docker kill jexevents
    - name: stop jex-events part 2
      ignore_errors: yes
      become: true
      shell: docker kill jex-events
