---
- name: Redeploy saved-searches
  hosts: saved-searches:&systems
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - services
    - colored
    - saved-searches
  roles:
    - role: util-notify-chat
      msg: "Deploying saved-searches"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{saved_searches.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying saved-searches"
