---
- name: Bring down Systemd DE Target
  hosts: docker-ready
  sudo: true
  gather_facts: false
  tags:
      - systemd
      - de-target
  roles:
      - role: de-systemd-de-target
        up: false

