---
- name: Redeploy tree-urls
  hosts: tree-urls:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - colored
    - tree-urls
  roles:
    - role: util-notify-chat
      msg: "Deploying tree-urls"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{tree_urls.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying tree-urls"
