---
- name: Redeploy templeton-incremental
  hosts: templeton-incremental:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - uncolored
    - templeton
    - templeton-incremental
  roles:
    - role: util-notify-chat
      when: not parasitic
      msg: "Deploying templeton-incremental"
    - role: de-deploy-service
      deploy_use_color: false
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      when: not parasitic
      service_name: "{{templeton_incremental.compose_service}}"
    - role: util-notify-chat
      when: not parasitic
      msg: ":heavy_check_mark: Done deploying templeton-incremental"
