### TODO CORE-7936: Remove after 2.8 release
---
- name: tag the apps in 'Beta' with 'beta' AVUs
  hosts: db-proxy:&systems
  become: true
  gather_facts: false
  tags:
    - databases
  roles:
    - role: util-notify-chat
      msg: "Adding app beta AVUs"
    - role: de-TMP-RUN-ONCE-app-beta-tagger
    - role: util-notify-chat
      msg: "Done adding app beta AVUs"
