---
- name: Redeploy user-preferences
  hosts: user-preferences:&systems
  become: true
  gather_facts: false
  any_errors_fatal: true
  tags:
    - services
    - colored
    - user-preferences
  roles:
    - role: util-notify-chat
      msg: "Deploying user-preferences"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{user_preferences.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying user-preferences"
