---
- name: Redeploy user-sessions
  hosts: user-sessions:&systems
  become: true
  gather_facts: false
  tags:
    - services
    - colored
    - user-sessions
  roles:
    - role: util-notify-chat
      msg: "Deploying user-sessions"
    - role: de-deploy-service
      deploy_use_color: "use_color|default(false)"
      has_configs: "{% if use_consul_configs %}{{ false }}{% else %}{{ true }}{% endif %}"
      service_name: "{{user_sessions.compose_service}}"
    - role: util-notify-chat
      msg: ":heavy_check_mark: Done deploying user-sessions"
