---
- name: Deploy Grouper
  hosts: grouper
  sudo: yes
  roles:
      - role: notify-chat
        username: Grouper
        icon: ":fish:"
        msg: "Deploying Grouper"

      - role: services-common
        tags: [ 'init_iplant_user' ]

      - role: grouper

      - role: notify-chat
        username: Grouper
        icon: ":fish:"
        msg: ":heavy_check_mark: Done deploying Grouper"
